name: ahenfie_media
description: "Ahenfie Radio and TV- Kumasi, Ghana"
publish_to: 'none'
version: 2.0.6+14

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Core Features
  just_audio: ^0.10.5
  just_audio_background: ^0.0.1-beta.10
  audio_service: ^0.18.10
  media_kit: ^1.1.11
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.5
  video_player: ^2.9.2
  chewie: ^1.11.0
  webview_flutter: ^4.7.0
  lottie: ^3.3.1
  wakelock_plus: ^1.3.2 
  shared_preferences: ^2.5.3
  upgrader: ^13.1.0
  package_info_plus: ^10.1.0
  path_provider: ^2.1.5
  screen_brightness: ^2.1.5


  # UI
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  font_awesome_flutter: ^11.0.0
  onesignal_flutter: ^5.2.0
  flutter_launcher_icons: ^0.14.4
  flutter_riverpod: ^3.0.3
  audio_session: ^0.2.2
  http: ^1.6.0
  intl: ^0.20.2
  xml: ^6.5.0
  supabase_flutter: ^2.9.0
  youtube_explode_dart: ^2.3.6
  youtube_player_iframe: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  change_app_package_name: ^1.5.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"


flutter:
  uses-material-design: true



  assets:
    - assets/images/logo.jpeg
    - assets/images/noti.png
    - assets/images/ahenfiefm.png
    - assets/images/9128828.jpg
    - assets/images/b92f2e77-722f-4236-9b18-6d31266aa9dd 2.jpg
    - assets/animations/nodata.json
    - assets/sounds/chime.mp3
    
